### ISSUE TITLE
Thank you for your outstanding work. Can you provide code?

### ISSUE THREAD

**Issue by wangSir0202** [SHTUPLUS/Pix2Grp_CVPR2024#1]
Hello, thank you very much for your excellent work, can you please share your source code？

**Comment by nchuly** [comment]
hi，have you gotten the code？i am excited for this too

**Comment by wangSir0202** [comment]
> hi，have you gotten the code？i am excited for this too

sorry nope.

**Comment by Scarecrow0** [comment]
We have uploaded the code of implementation.
