### ISSUE TITLE
Missing file - categories_dict.json

### ISSUE THREAD

**Issue by vineet2104** [SHTUPLUS/Pix2Grp_CVPR2024#2]
Hi, I'm trying to train your model on the Visual Genome Dataset to reproduce the results for closed vocabulary SGG. The config file mentions the categories_dict.json file in the vg_motif_anno folder but I could not find the source for this file. 

Can you please check if this file is missing or if there is a script to generate this file?

**Comment by Scarecrow0** [comment]
We have added the missing files [here](https://github.com/SHTUPLUS/Pix2Grp_CVPR2024/tree/main/all_categories_dict).
Thanks for noticing us.
