### ISSUE TITLE
Clarification about the metrics in the output of this repo.

### ISSUE THREAD

**Issue by jkli1998** [SHTUPLUS/Pix2Grp_CVPR2024#4]
Thanks for sharing this impressive work! 
I have two questions.

1. I'm confused about the numbers output by this repo. How do all these outputs correspond to the thesis metrics (close/open-set) ?  Can you explain them?
2. How to choose the open vocabulary predicates? Can you point them out in the code? Does this work contain open vocabulary object detection?

Thank you in advance. Looking forward to your reply.

**Comment by Scarecrow0** [comment]
1. There are two primary parts for evaluation. One is the standard mean recall and recall of the SGG task. Additionally, the standard evaluation metric is the mean recall for novel classes.
2. We randomly select novel classes with more than 10 instances in the test set.
